//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredictingSoccer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PredictingSoccer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOU,AVL,4390,1,8678,10252,0,1,2015-08-08 00:00:00
        ///CHE,SWA,4391,1,8455,10003,2,2,2015-08-08 00:00:00
        ///EVE,WAT,4392,1,8668,9817,2,2,2015-08-08 00:00:00
        ///LEI,SUN,4393,1,8197,8472,4,2,2015-08-08 00:00:00
        ///MUN,TOT,4394,1,10260,8586,1,0,2015-08-08 00:00:00
        ///NOR,CRY,4396,1,9850,9826,1,3,2015-08-08 00:00:00
        ///ARS,WHU,4389,1,9825,8654,0,2,2015-08-09 00:00:00
        ///NEW,SOU,4395,1,10261,8466,2,2,2015-08-09 00:00:00
        ///STK,LIV,4397,1,10194,8650,0,1,2015-08-09 00:00:00
        ///WBA,MCI,4398,1,8659,8456,0,3,2015-08-10 00:00:00
        ///AVL,MUN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string england15 {
            get {
                return ResourceManager.GetString("england15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARS,WBA,4319,38,9825,8659,4,1,2015-05-24 00:00:00,2014/2015
        ///AVL,BUR,4320,38,10252,8191,0,1,2015-05-24 00:00:00,2014/2015
        ///CHE,SUN,4321,38,8455,8472,3,1,2015-05-24 00:00:00,2014/2015
        ///CRY,SWA,4322,38,9826,10003,1,0,2015-05-24 00:00:00,2014/2015
        ///EVE,TOT,4323,38,8668,8586,0,1,2015-05-24 00:00:00,2014/2015
        ///HUL,MUN,4324,38,8667,10260,0,0,2015-05-24 00:00:00,2014/2015
        ///LEI,QPR,4325,38,8197,10172,5,1,2015-05-24 00:00:00,2014/2015
        ///MCI,SOU,4326,38,8456,8466,2,0,2015-05-24 00:00:00,2014/2015
        ///NEW,WHU,4327,38,1026 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string englandupto15 {
            get {
                return ResourceManager.GetString("englandupto15", resourceCulture);
            }
        }
    }
}
