//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND,KOR,1673,30,8635,8571,3,0,2016-03-13 00:00:00,2015/2016,1.67,4,4.75
        ///GEN,OOS,1674,30,9987,8573,4,1,2016-03-13 00:00:00,2015/2016,1.65,3.9,5
        ///MEC,STL,1675,30,8203,9985,4,0,2016-03-13 00:00:00,2015/2016,4.3,3.9,1.75
        ///ZUL,MOP,1676,30,10000,274581,3,0,2016-03-13 00:00:00,2015/2016,1.83,3.8,4
        ///CHA,GEN,1677,30,9986,9991,1,1,2016-03-13 00:00:00,2015/2016,3.5,3.5,2.05
        ///O-H,CLB,1678,30,1773,8342,0,1,2016-03-13 00:00:00,2015/2016,3.2,3.7,2.1
        ///WES,WAA,1679,30,10001,8475,1,0,2016-03-13 00:00:00,2015/2016,1.8,3.9,4        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bel {
            get {
                return ResourceManager.GetString("bel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUN,BOU,4702,38,10260,8678,3,1,2016-05-17 00:00:00,2015/2016,1.67,4.1,5.2
        ///ARS,AVL,4699,38,9825,10252,4,0,2016-05-15 00:00:00,2015/2016,1.15,9,21
        ///CHE,LEI,4700,38,8455,8197,1,1,2016-05-15 00:00:00,2015/2016,2.3,3.75,3.1
        ///EVE,NOR,4701,38,8668,9850,3,0,2016-05-15 00:00:00,2015/2016,1.8,3.9,4.6
        ///NEW,TOT,4703,38,10261,8586,5,1,2016-05-15 00:00:00,2015/2016,4.6,4,1.75
        ///SOU,CRY,4704,38,8466,9826,4,1,2016-05-15 00:00:00,2015/2016,1.33,5.5,10
        ///STK,WHU,4705,38,10194,8654,2,1,2016-05-15 00:00:00,2015/2016,3.5,3.8,2.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eng {
            get {
                return ResourceManager.GetString("eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANG,TOU,7739,38,8121,9941,2,3,2016-05-14 00:00:00,2015/2016,4.5,3.6,1.85
        ///MON,MON,7740,38,9829,10249,2,0,2016-05-14 00:00:00,2015/2016,1.4,4.8,8
        ///ETI,LIL,7741,38,9853,8639,0,1,2016-05-14 00:00:00,2015/2016,2.45,3.13,3.2
        ///GUI,NIC,7742,38,9747,9831,2,3,2016-05-14 00:00:00,2015/2016,4.4,3.75,1.83
        ///TRO,MAR,7743,38,10242,8592,1,1,2016-05-14 00:00:00,2015/2016,4.8,4.33,1.67
        ///LOR,GAJ,7744,38,8689,6391,1,0,2016-05-14 00:00:00,2015/2016,3.1,3.5,2.3
        ///PSG,NAN,7745,38,9847,9830,4,0,2016-05-14 00:00:00,2015/2016,1.29,6, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fra {
            get {
                return ResourceManager.GetString("fra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMU,HAN,10194,34,9823,9904,3,1,2016-05-14 00:00:00,2015/2016,1.13,10,20
        ///DOR,FCK,10195,34,9789,8722,2,2,2016-05-14 00:00:00,2015/2016,1.3,6,9.5
        ///LEV,ING,10196,34,8178,8234,3,2,2016-05-14 00:00:00,2015/2016,1.53,4.75,5.75
        ///WOL,STU,10197,34,8721,10269,3,1,2016-05-14 00:00:00,2015/2016,2.38,4.1,2.7
        ///AUG,HAM,10198,34,8406,9790,1,3,2016-05-14 00:00:00,2015/2016,2,3.7,3.7
        ///WBR,EFR,10199,34,8697,9810,1,0,2016-05-14 00:00:00,2015/2016,2,3.8,3.6
        ///HOF,S04,10200,34,8226,10189,1,4,2016-05-14 00:00:00,2015/2016,3,3.9,2. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ger {
            get {
                return ResourceManager.GetString("ger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAM,EXC,15659,34,7788,10218,0,2,2016-05-08 00:00:00,2015/2016,3.3,3.8,2.05
        ///UTR,ALK,15660,34,9908,10229,1,3,2016-05-08 00:00:00,2015/2016,2.3,3.9,2.8
        ///FEY,NEC,15661,34,10235,8464,1,0,2016-05-08 00:00:00,2015/2016,1.45,4.75,6.25
        ///ZWO,PSV,15662,34,6413,8640,1,3,2016-05-08 00:00:00,2015/2016,6.5,5.4,1.4
        ///GRA,AJA,15663,34,8526,8593,1,1,2016-05-08 00:00:00,2015/2016,17,8.5,1.14
        ///ROD,WII,15664,34,9803,8525,2,3,2016-05-08 00:00:00,2015/2016,3.1,3.7,2.2
        ///GRO,HER,15665,34,8674,9791,2,1,2016-05-08 00:00:00,2015/2016, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ned {
            get {
                return ResourceManager.GetString("ned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOR,MAR,19634,34,8348,10212,2,1,2016-05-15 00:00:00,2015/2016,2.1,3.5,3.25
        ///BEN,NAC,19638,34,9772,10214,4,1,2016-05-15 00:00:00,2015/2016,1.1,9,21
        ///BRA,SCP,19639,34,10264,9768,0,4,2016-05-15 00:00:00,2015/2016,6.25,4.33,1.5
        ///TON,ACA,19631,34,188163,10215,2,0,2016-05-14 00:00:00,2015/2016,1.6,4.1,5.5
        ///POR,BOA,19632,34,9773,8613,4,0,2016-05-14 00:00:00,2015/2016,1.29,5.5,11
        ///SET,FER,19633,34,10238,6403,0,0,2016-05-14 00:00:00,2015/2016,2.45,3.2,3
        ///MAD,RA,19635,34,6367,7841,1,2,2016-05-14 00:00:00,2015/2016,2. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string por {
            get {
                return ResourceManager.GetString("por", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string sco {
            get {
                return ResourceManager.GetString("sco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPG,VIL,24490,38,9869,10205,2,0,2016-05-15 00:00:00,2015/2016,1.45,4.6,8
        ///BET,GET,24491,38,8603,8305,2,1,2016-05-15 00:00:00,2015/2016,5,4,1.73
        ///ESP,EIB,24492,38,8558,8372,4,2,2016-05-15 00:00:00,2015/2016,2.05,3.7,3.75
        ///MAL,LAS,24495,38,9864,8306,4,1,2016-05-15 00:00:00,2015/2016,1.85,3.8,4.4
        ///RAY,LEV,24497,38,8370,8581,3,1,2016-05-15 00:00:00,2015/2016,1.33,5.75,9
        ///COR,REA,24489,38,9783,8633,0,2,2016-05-14 00:00:00,2015/2016,13,8.5,1.2
        ///GRA,BAR,24493,38,7878,8634,0,3,2016-05-14 00:00:00,2015/2016,31,13,1. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spa {
            get {
                return ResourceManager.GetString("spa", resourceCulture);
            }
        }
    }
}
